id: first_fail_make_test_pass
learningObjectives:
  - Find all the tests scenarios
hints:
  - ??
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: https://media.tenor.com/KQru_VOmJxcAAAAC/bird-knife.gif
            delay: 2000
          - text: Now it’s time to **implement the isValidUrl function and use it when creating new items**, to make those tests pass from RED to GREEN!
            delay: 2000
          - text: 'Send a PR when you are done'
            delay: 1000

githubActions:
  backend:
    capabilities:
      - axios
      - dotenv
    testFile: testAddItems.js
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: '${eventType}'
      cases:
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Umm… something is not quite right, please take another look and try again.
                    delay: 2500
        github_pr_workflow_complete_success:
          if:
              conditions:
              - conditionId: github_is_file_added
                params:
                  fileName: backend/tests/unit/models/item.test.js
                onFalseParams:
                  checks_failed_message: Your test file is missing. Can you check it?
                  
              - conditionId: github_is_file_added
                params:
                  fileName: backend/utils/urlValidate.js
                onFalseParams:
                  checks_failed_message: urlValidate.js is missing. Can tou check it?
                  
              - conditionId: github_is_file_modified
                params:
                  fileName: backend/items/api/items.js
                onFalseParams:
                  checks_failed_message: items.js should be mofigied to use the new url validator.
                    
              then:
                do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: Amazing. You can now merge the PR
                        delay: 1500

                - actionId: github_pr_approve
                  params:
                    person: keen
                    message: Amazing. You can now merge the PR
              else:
                do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: ${checks_failed_message}
                        delay: 2500
                - actionId: github_pr_reject
                  params:
                    person: keen
                    message: ${checks_failed_message}

        github_pr_merged:
          do:
            - actionId: finish_step
