id: first_fail_answer_question
learningObjectives:
  - Getting familiar with modern methodologies
  - Build your confidence around your code
hints:
  - In the TDD methodology we start by writing...
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: We have something wrong with some items images 😱 \n I just realized we're not validating new items image URLs, and users keep uploading weird furby GIFs!
            delay: 2000
          - text: https://media.tenor.com/KE-5C3oI__kAAAAd/furby-cut.gif
            delay: 3500
          - text: like this ^ only creepier 
            delay: 3500
          - text: Of course we're going to fix the bug, but we want to be confident that it won't happen again.. \n What do you think should be our first step?
            delay: 3500
trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    if:
      conditions:
        - conditionId: text_match_regex
          params:
            text: '${userMessageText}'
            regex: test|tdd
      then:
        do:
          - actionId: bot_message
            params:
              person: keen
              messages:
                - text: Great! Yalla lets add some tests 🚀
                  delay: 1300
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: keen
              messages:
                - text: mmm... not what I had in mind. \n Here you can find more information about our[favorite methodology](https://youtu.be/u6QfIXgjwGQ).
                  delay: 2500
                - text: So, what do you think should be our first step?
                  delay: 2500
